"use client";
import {useCallback,useEffect,useState,type FormEvent} from "react";
type Json=Record<string,unknown>;
type Experiment={id:string;state:string;spec:Json;review_digest:string;entities:Json;metrics:Json[];error:string|null};
async function request<T>(path:string,body?:unknown):Promise<T>{const r=await fetch('/api/v2'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
export default function MetaPanel({runId,creativeId}:{runId:string;creativeId:string}){
 const [experiments,setExperiments]=useState<Experiment[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState(''),[since,setSince]=useState(''),[until,setUntil]=useState('');
 const refresh=useCallback(async()=>setExperiments(await request<Experiment[]>('/experiments')),[]);
 useEffect(()=>{void refresh().catch(e=>setError(String(e)));const t=setInterval(()=>void refresh().catch(e=>setError(String(e))),7000);return()=>clearInterval(t);},[refresh]);
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await refresh();setConfirmation('');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function draft(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);await act(()=>request('/experiments',{run_id:runId,creative_id:creativeId,ad_account_id:data.get('account'),page_id:data.get('page'),destination:data.get('destination'),daily_budget_minor:Number(data.get('budget')),currency:data.get('currency'),audience:JSON.parse(String(data.get('audience'))),message:data.get('message'),headline:data.get('headline'),special_ad_categories:String(data.get('categories')||'').split(',').map(x=>x.trim()).filter(Boolean),research_license_approved_for_commercial_use:data.get('license')==='on'}));}
 return <><section className="nl-panel"><h2>A human-reviewed handoff. Always paused.</h2><p>This integration can create actual Meta campaign, ad-set and ad objects only after explicit approval. It never activates delivery, edits billing, or increases spend. Activation, when appropriate, is a separate manual Ads Manager action.</p>{error&&<p className="nl-error" role="alert">{error}</p>}{!runId||!creativeId?<div className="nl-empty">Select an evaluated creative in a completed run before drafting a deployment.</div>:<form className="nl-form" onSubmit={e=>void draft(e)}><label>Ad account ID<input name="account" required pattern="(act_)?[0-9]+"/></label><label>Page ID<input name="page" required pattern="[0-9]+"/></label><label>Daily budget (account minor units)<input name="budget" type="number" min={100} max={1000000} required/></label><label>Account currency<input name="currency" required pattern="[A-Z]{3}" maxLength={3}/></label><label className="wide">HTTPS destination<input name="destination" type="url" required pattern="https://.*"/></label><label>Headline<input name="headline" maxLength={255} required/></label><label>Special ad categories (comma-separated)<input name="categories" placeholder="Review requirements; blank declares none"/></label><label className="wide">Ad message<textarea name="message" required maxLength={2000}/></label><label className="wide">Audience targeting JSON<textarea name="audience" required placeholder='Use your reviewed Meta targeting specification.'/></label><label className="wide nl-checkbox"><input name="license" type="checkbox" required/> I reviewed model/media licenses, advertising claims, special-category requirements, audience, destination and budget for this commercial use.</label><p className="wide nl-note">Creative {creativeId}. A draft is not approval and does not make a remote API call. The next review includes the exact asset hash and immutable specification.</p><button className="nl-button primary" disabled={busy}>Create review draft</button></form>}</section>
 <section className="nl-panel"><h2>Deployment review and real reports</h2>{experiments.length===0&&<p>No experiments have been created.</p>}{experiments.map(e=><article className="nl-evaluator" key={e.id}><h3>{e.id.slice(0,8)} · {e.state.replaceAll('_',' ')}</h3>{e.error&&<p className="nl-error">{e.error}</p>}<details><summary>Inspect exact creative, destination, budget, audience and review digest</summary><pre className="nl-json">{JSON.stringify({spec:e.spec,review_digest:e.review_digest},null,2)}</pre></details><details><summary>Remote IDs and readback receipts</summary><pre className="nl-json">{JSON.stringify(e.entities,null,2)}</pre></details>{e.state==='DRAFT'&&<label>Type APPROVE PAUSED DEPLOYMENT<input aria-label="Approval confirmation" value={confirmation} onChange={x=>setConfirmation(x.target.value)}/><button className="nl-button" disabled={busy||confirmation!=='APPROVE PAUSED DEPLOYMENT'} onClick={()=>void act(()=>request(`/experiments/${e.id}/approve`,{review_digest:e.review_digest,confirmation}))}>Approve this exact review</button></label>}{['APPROVED','FAILED'].includes(e.state)&&<label>Type DEPLOY PAUSED<input aria-label="Deployment confirmation" value={confirmation} onChange={x=>setConfirmation(x.target.value)}/><button className="nl-button" disabled={busy||confirmation!=='DEPLOY PAUSED'} onClick={()=>void act(()=>request(`/experiments/${e.id}/deploy`,{review_digest:e.review_digest,confirmation}))}>Queue paused deployment</button></label>}{['DEPLOYED','INCONCLUSIVE','COLLECTING'].includes(e.state)&&<div className="nl-controls"><label>Since<input type="date" value={since} onChange={x=>setSince(x.target.value)}/></label><label>Until<input type="date" value={until} onChange={x=>setUntil(x.target.value)}/></label><button className="nl-button" disabled={busy||!since||!until} onClick={()=>void act(()=>request(`/experiments/${e.id}/insights?since=${encodeURIComponent(since)}&until=${encodeURIComponent(until)}`,{}))}>Retrieve actual insights</button></div>}<details><summary>Stored reports — no automatic winner claim</summary><pre className="nl-json">{JSON.stringify(e.metrics,null,2)}</pre></details></article>)}</section></>;
}
