"""Initial durable NeuroLoop schema. Destructive downgrade is operator-only."""
from alembic import op
import sqlalchemy as sa
revision="20260912_01"
down_revision=None
branch_labels=None
depends_on=None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notebook_workers',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('workload_approved', sa.Boolean(), nullable=False),
    sa.Column('heartbeat_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=250), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('selected_ids', sa.JSON(), nullable=False),
    sa.Column('champion_id', sa.String(length=36), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_campaign_runs_campaign_id'), 'campaign_runs', ['campaign_id'], unique=False)
    op.create_table('creative_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('upload_key', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('upload_key')
    )
    op.create_index(op.f('ix_creative_assets_campaign_id'), 'creative_assets', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_creative_assets_job_id'), 'creative_assets', ['job_id'], unique=False)
    op.create_table('creatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('branch', sa.Integer(), nullable=False),
    sa.Column('creation_type', sa.String(length=30), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('input_asset_ids', sa.JSON(), nullable=False),
    sa.Column('output_asset_id', sa.String(length=36), nullable=True),
    sa.Column('generation', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('attribution_quality', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['output_asset_id'], ['creative_assets.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['campaign_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creatives_campaign_id'), 'creatives', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_creatives_run_id'), 'creatives', ['run_id'], unique=False)
    op.create_table('meta_experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('review_digest', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.Float(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['campaign_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_experiments_run_id'), 'meta_experiments', ['run_id'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['campaign_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    op.create_table('weave_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('exception', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.Float(), nullable=False),
    sa.Column('ended_at', sa.Float(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('delivered_revision', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['campaign_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weave_outbox_run_id'), 'weave_outbox', ['run_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('creative_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=250), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.Float(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('lease_hash', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.Float(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['campaign_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_generation_jobs_capability'), 'generation_jobs', ['capability'], unique=False)
    op.create_index(op.f('ix_generation_jobs_run_id'), 'generation_jobs', ['run_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_status'), 'generation_jobs', ['status'], unique=False)
    op.create_index('ix_jobs_claim', 'generation_jobs', ['status', 'available_at', 'capability'], unique=False)
    op.create_table('human_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('creative_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_feedback_campaign_id'), 'human_feedback', ['campaign_id'], unique=False)
    op.create_table('intervention_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creative_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('context_key', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=160), nullable=False),
    sa.Column('observation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['campaign_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creative_id')
    )
    op.create_index(op.f('ix_intervention_ledger_campaign_id'), 'intervention_ledger', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_intervention_ledger_context_key'), 'intervention_ledger', ['context_key'], unique=False)
    op.create_index(op.f('ix_intervention_ledger_run_id'), 'intervention_ledger', ['run_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('applied_action', sa.String(length=40), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['campaign_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_decisions_run_id'), 'decisions', ['run_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('creative_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('evaluator', sa.String(length=40), nullable=False),
    sa.Column('comparison_key', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['campaign_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_evaluations_creative_id'), 'evaluations', ['creative_id'], unique=False)
    op.create_index(op.f('ix_evaluations_run_id'), 'evaluations', ['run_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_run_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_creative_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_decisions_run_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_intervention_ledger_run_id'), table_name='intervention_ledger')
    op.drop_index(op.f('ix_intervention_ledger_context_key'), table_name='intervention_ledger')
    op.drop_index(op.f('ix_intervention_ledger_campaign_id'), table_name='intervention_ledger')
    op.drop_table('intervention_ledger')
    op.drop_index(op.f('ix_human_feedback_campaign_id'), table_name='human_feedback')
    op.drop_table('human_feedback')
    op.drop_index('ix_jobs_claim', table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_status'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_run_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_capability'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_weave_outbox_run_id'), table_name='weave_outbox')
    op.drop_table('weave_outbox')
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_meta_experiments_run_id'), table_name='meta_experiments')
    op.drop_table('meta_experiments')
    op.drop_index(op.f('ix_creatives_run_id'), table_name='creatives')
    op.drop_index(op.f('ix_creatives_campaign_id'), table_name='creatives')
    op.drop_table('creatives')
    op.drop_index(op.f('ix_creative_assets_job_id'), table_name='creative_assets')
    op.drop_index(op.f('ix_creative_assets_campaign_id'), table_name='creative_assets')
    op.drop_table('creative_assets')
    op.drop_index(op.f('ix_campaign_runs_campaign_id'), table_name='campaign_runs')
    op.drop_table('campaign_runs')
    op.drop_table('strategy_policies')
    op.drop_table('notebook_workers')
    op.drop_table('campaigns')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
